from numpy.typing import NDArray


def create_lammps_struct_file(
    xhi: float,
    yhi: float,
    zhi: float,
    xy: float,
    xz: float,
    yz: float,
    frac_coords: NDArray,
) -> str:
    """Create structure file for LAMMPS

    Args:
        xhi (float): The parameter about system.
        yhi (float): The parameter about system.
        zhi (float): The parameter about system.
        xy (float): The tilt parameter.
        xz (float): The tilt parameter.
        yz (float): The tilt parameter.
        frac_coords (NDArray): The fractional coordinates of all the atoms.
            The shape is (n_atom, 3).

    Returns:
        str: The content of a structure file.
    """
    # Create system section
    n_atom = frac_coords.shape[0]
    lines = [
        "# generated by struct-searcher",
        "",
        f"{n_atom} atoms",
        "1 atom types",
        "",
        f"0.0 {xhi:.15f} xlo xhi",
        f"0.0 {yhi:.15f} ylo yhi",
        f"0.0 {zhi:.15f} zlo zhi",
        "",
        f"{xy:.15f} {xz:.15f} {yz:.15f} xy xz yz",
        "",
    ]

    # Create Atoms section
    atoms_section = ["Atoms", ""]
    for i, coords in enumerate(frac_coords.tolist(), 1):
        coords_str = " ".join("{:.15f}".format(coord) for coord in coords)
        line = f"{i} 1 {coords_str}"
        atoms_section.append(line)
    atoms_section.append("")

    lines.extend(atoms_section)
    content = "\n".join(lines)

    return content
